services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped

    env_file:
      - ./backend/.env
    environment:
      - HF_HOME=/tmp/hf
      - TRANSFORMERS_CACHE=/tmp/hf/transformers
      - HF_HUB_CACHE=/tmp/hf/hub

    ports:
      - "8000:8000"

    networks:
      - sentexa_network

    volumes:
      - ./backend/app:/app/app
      - ./backend/ml/checkpoints:/app/ml/checkpoints

    security_opt:
      - no-new-privileges:true

    develop:
      watch:
        - action: sync
          path: ./backend/app
          target: /app/app
          ignore:
            - __pycache__/
            - "*.pyc"
            - .pytest_cache/
            - .ruff_cache/

        - action: sync
          path: ./backend/ml/checkpoints
          target: /app/ml/checkpoints

        - action: rebuild
          path: ./backend/requirements/production.txt

        - action: rebuild
          path: ./backend/requirements/base.txt

        - action: rebuild
          path: ./backend/Dockerfile

        - action: rebuild
          path: ./backend/alembic.ini

networks:
  sentexa_network:
    driver: bridge
